@startuml

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

'hide circle
hide empty members
hide empty methods


abstract class MyCharacter {
fight() {this.weapon.useWeapon();}
setWeapon(BehaviorWeapon a) {this.weapon = a;}
}
class Queen {
fight() {...}
}
class King {
fight() {...}
}
class BehaviorPoignard {
}
class BehaviorBow {
}
class BehaviorSword {
}
interface BehaviorWeapon{
{abstract} useWeapon()
}
class Troll {
fight() {...}
}
class Chevalier {
fight() {...}
}
MyCharacter <|-- King
MyCharacter <|-- Queen
MyCharacter <|-- Chevalier
MyCharacter <|-- Troll
MyCharacter o--> "1" BehaviorWeapon

BehaviorWeapon <|.. BehaviorSword
BehaviorWeapon <|.. BehaviorPoignard
BehaviorWeapon <|.. BehaviorBow


@enduml
